apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ""
    credentials.json: ENC[AES256_GCM,data:BJbgDV/M9WZDcFbS2PySwTyopNw3Rm26TCpIP12wn9qyUZPhuXjr6abZiRlKnqNqSwoBsfOxd6CDggTOQara,iv:f9Az+SSrwQU13MARye+qMJ7pYS2Kkkm1lj0NuY+8EfI=,tag:0vmM/luZiJJRwH7ecP8Bag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mmjl968l88scrlpa8uf26840gag07hmn0w08slr80fcky4gzdfxq2frdr0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SkRVUEhlV1VFRU1SZVdR
            M1dXY01TS0JYcWlOMnJNalR6ZXRBdmI4M1dFCjJ1N3BvajNJdWIrRnpVaTZodmFJ
            TTFxbUI4ZTRvamo5ZG1qUHVHTUxreTAKLS0tIGIxbXpLMU96Tkg2OHFtRDk0ZUhj
            WFRmVEZMNVJJQmM4c2NnR0tCOHlqM0kKHQrvxJw+HVDkKu18DyPkja5+8fN+l4aL
            KsYC/YBKc0pfCElxPQRKY1FYDJW/3pcuriLnb8Y8ZmWsmbtxy/lKCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-27T09:23:19Z"
    mac: ENC[AES256_GCM,data:7/ULC/I3tAqdrRj5K9AUvAa4In0zAZCKt003pIjOJPpkf5dwGRBdh8jP80jE77MjScbRKJYCG0JTO6+JVowhxoWrN6Po2RJ/Y5zj5EFC1eKr1s6xt6bgsII2f0SxGsG6PtvsrH0772CBV7VNZ0ERROukFwk1WXGlwt+nj6tHt80=,iv:XygX056NpcU6j422XmYTXA1K0ArT5vbNE5qhwm/bqX0=,tag:w8zanE2rZ8x3+kmyqRd3qA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
