apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
    SECRET_ACME_EMAIL: ""
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mmjl968l88scrlpa8uf26840gag07hmn0w08slr80fcky4gzdfxq2frdr0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M0ZLeVhiVk14K2sxWFdI
            NWNOZHEzZXJFOGxMbzhZeDNQckMwZWwrZ1RnCnZNYy9EWTdkWWp6UzMyNkZvY1I3
            MDI4eXlIOEtOWWlZemNGdEo1K09DYzgKLS0tIDg3bVR6NVVMV1dFejhQU1pUN2hp
            QmtPZCtzcEw2TnVtUm1YOGF1ZWh2YjgKth1teotYXv18nST0Mu+9P60u2uGKSm+0
            wLHaHvA7tnO9yZRBf/jZ7jRxT1YxB/hj1cn+sRuFIzSQyKNV42fSrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-27T11:58:11Z"
    mac: ENC[AES256_GCM,data:8vvBIjJhyDxB0M4PcBvbSBw2CwtRxpYBhmQXHzJne/8n15V0Xbhgno3Rlp4USv7EfZO9ManJp7ONHPCNjHELjyCCznw/0ugtJBWGnKCmYaK2TZC0IKi0J8l4I3LHBLrnonUupIO/OasQjU+GMcw16BtyufDB0TdG6KmSpybb4tw=,iv:L85oF5SE/HxkZoO/fPH9GQ+tgpgAbfENhFa2SZACDUU=,tag:j5439pccNbFGv99HZjDGlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
