apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:rBgX2kzjtmvieiZIUtcMfskLVIL860LFLvhg7wTAd7A=,iv:WoQ49+xvysJdMn+s5H2XM0rZVTpk4nmdGEdudj5myMc=,tag:iSdXyYaI2r9jtNcOMjocCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mmjl968l88scrlpa8uf26840gag07hmn0w08slr80fcky4gzdfxq2frdr0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z3Y4Y2IrSU8zNk1ZaEtl
            SGVRWnJ3Z3NzRWphQy92Y3k0alcwUWVBbUNFClQvVW1KaGVscUhtdUlGMkZLRDRL
            S0V4bU1jR255ZlpDaXNCQzdJc203QU0KLS0tIGVTaGoxVkdZaERIWjJzTjBkMTJD
            ZzBaYTN6WWVNeEg0N04rY3lEYysrZlEKSRgj4WLrwaTU6K1D40ylDtF6/3+v9iPQ
            Kl4WvlbbOB4FDgXL37QHJCK0pgrbMy0fQDk/AG0dnqe7RBT3592uNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-27T11:58:11Z"
    mac: ENC[AES256_GCM,data:8CpBsQaFOOpbQdkuGOn/1lRK++gnq4qZDfSMNK8VJfoN/slzsko5xIceBNOAmLzU3VoXuUuI0VP25UtBER5tzfIFV289SmKP/uQErK/Xev0fyyA+cDxcC305sQ7hlE7dzzWibR3mPkQAsuoHGuEcvNbtQv6sm8WbbZYKRoZhXbg=,iv:rFRA5uiH7klj5hx55XQwNYeVU2MEUxnjPcNpCvaw38w=,tag:92NUxkrb3/XJAhW5nNataA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
