apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mmjl968l88scrlpa8uf26840gag07hmn0w08slr80fcky4gzdfxq2frdr0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNjhlOEQyR1dldFgwMDRZ
            MWlldkMweEI1V1VMUWtZOFNoQldtNkdpVldzCnMrb1VUd25Xd3VHY3pYTTVCdHYr
            WnloeGlJUFVWNy9iYUIyQXg0UXJPRVEKLS0tIHJjZnhwZW9ScUZTckQ1cm04U2hG
            eE40TWE0akduaWJkZnplVmVIcmNSMzgKl2yFfSH0SusmtNlyX/59iUl6Q0U49wpH
            2X5d6BoIrDcJYMWYE+7nelhyPmGbcgp4a3EkPWA3sU6B1GGmONphVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-27T09:23:19Z"
    mac: ENC[AES256_GCM,data:BCjRB75sVU0CLxGxDCAP/bHvK2tRO3BykVGD+fBQip+8w3/lPYsJSSqFY/7+1rr1hFviEx0oEvaYrpi0q7esj443BIOQWYpjiqVnqFViMNhgTkTiRpbqYb13i7mrrrginhCRPsg6gMpPI1JtGJuxgyM+qq4UOFDPbTiFSZ10Y9Q=,iv:u8UuF/w1WbxqJKGKO3tV63YlDntUGBCyJ4ugdfsjsAM=,tag:7y6nPkqAtCkwDyqeRWgIZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
